supermetrics-public/pecl-jsonpath

jsonpath.c
src/jsonpath/lexer.c

- Remove all `if/else` blocks that deal with PHP 5.x
- Minor tweaks to get the code compiling in PHP 7.4, most notably `php_pcre_match_impl()` interface changes

Remove PHP 5.x code and add support for PHP 7.4

---

jsonpath.c

Including the version number in the info makes it easier for people to know which version of the extension is installed.

Add extension version number to info output

---

jsonpath.c
src/jsonpath/lexer.c
src/jsonpath/parser.c

Adds various improvements to the array slice expression:
- Negative indexes to reference elements from the end of the list, for example `-1` to reference the last element
- Step parameter, for example `[0:5:2]` to target the first, third and fifth element in an array
- Start, end, and step are all optional, with the following defaults:
- start: `0`, beginning of list
- end: `0`, end of list, inclusive
- step: `1`
- Examples: `[1:]` to skip the first element, `[0:-2]` to skip the last two elements, `[::3]` to pick every third element

Add negative indexes, step parameter, and default values for array slicing

---

jsonpath.c
src/jsonpath/lexer.c
src/jsonpath/lexer.h
src/jsonpath/parser.c
src/jsonpath/parser.h

- Dirty hack to support boolean `true` and `false` in filter expressions, for example `$.store.book[?(@.in_stock == true)]`
- Rudimentary support for wildcard with recursive descent, `$..*` to return all leaf nodes in the JSON structure

Parse literal booleans separately for more accurate comparisons, add rudimentary support for wildcard operator with recursive descent

---

jsonpath.c
src/jsonpath/parser.c

Debugger output examples:
```
==1349069== Conditional jump or move depends on uninitialised value(s)
==1349069==    at 0x484CE5B: zim_JsonPath_find (jsonpath.c:97)
==1349069==    by 0x67DCD5: ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER (zend_vm_execute.h:1863)
==1349069==    by 0x6ED1D7: execute_ex (zend_vm_execute.h:54560)
==1349069==    by 0x6F2924: zend_execute (zend_vm_execute.h:58875)
==1349069==    by 0x643968: zend_execute_scripts (zend.c:1680)
==1349069==    by 0x5A4F4B: php_execute_script (main.c:2488)
==1349069==    by 0x733028: do_cli (php_cli.c:949)
==1349069==    by 0x734076: main (php_cli.c:1336)
==1349069==  Uninitialised value was created by a stack allocation
==1349069==    at 0x484CB42: zim_JsonPath_find (jsonpath.c:31)
```
```
==1354633== Invalid read of size 1
==1354633== …
```

Fix some initialization and read-after-release errors found with the debugger

---

.github/workflows/build.yml

Although PHP 8.1 isn't released yet, it's good to be aware of any issues beforehand.

Test the build with PHP nightly (8.1) as well

---

src/jsonpath/lexer.c

Allows for floats in expressions, for example `$..book[?(@.price < 8.97)]`.

Add support for literal floats in lexer, with point as decimal separator

---

src/jsonpath/parser.c

Fixes this warning:
```
.../jsonpath/src/jsonpath/parser.c: In function ‘convert_to_postfix’:
.../jsonpath/src/jsonpath/parser.c:400:9: warning: implicit declaration of function ‘get_operator_precedence’ [-Wimplicit-function-declaration]
400 |     if (get_operator_precedence(expr_in[i].type) > get_operator_precedence((*expr_tmp).type)) {
|         ^~~~~~~~~~~~~~~~~~~~~~~
```

Fix compile warning about implicit function declaration of get_operator_precedence()

---

jsonpath.c
src/jsonpath/parser.c

This makes it possible to use array slicing on the root node, for example `$[0:10:2]` to get every second element of the first 10 elements in the array.

Add support for range filtering on root node

---

jsonpath.c

I got the following compilation error under PHP 7.4 on MacOS Mojave:
```
/Users/mike/dev/php-ext-jsonpath/jsonpath.c:172:5: error: use of undeclared identifier 'ulong'
ulong num_key;
```
Looks like this is due to a breaking change in PHP 7.4.
See [the PHP 7.4 internals upgrade notes](https://github.com/php/php-src/blob/PHP-7.4/UPGRADING.INTERNALS#L24).

misc: replace ulong with zend_ulong

---

jsonpath.c
tests/overflow/002.phpt

Parsed tokens are copied to an array of fixed length `PARSE_BUF_LEN`. The token scan routine fails if more than `PARSE_BUF_LEN` tokens are parsed because there is no bounds check.
In the future, the scan routine should probably be refactored to copy tokens into a dynamically-sized array.
**Update**
I also took the opportunity to decompose and clean up the `find()` method a bit.

misc: fix array out of bounds bug

---

jsonpath.c
src/jsonpath/parser.c

Fixes all the valgrind errors reported by `TEST_PHP_ARGS="-q -m" make test`.
Tests fixed:
```
< Test typical use cases [tests/001.phpt]
< Test typical use cases [tests/003.phpt]
< Ensure no segfault if filtering on object instead of array [tests/005.phpt]
< Ensure no "Array to string conversion" notice when selecting non-scalar [tests/006.phpt]
< Test bracket notation [tests/comparison_bracket_notation/001.phpt]
< Test bracket notation on object without key [tests/comparison_bracket_notation/002.phpt]
< Test bracket notation with NFC path on NFD key [tests/comparison_bracket_notation/004.phpt]
< Test bracket notation with dot [tests/comparison_bracket_notation/005.phpt]
< Test bracket notation with double quotes [tests/comparison_bracket_notation/006.phpt]
< Test bracket notation with …
```

Fix valgrind errors

---

tests/comparison_misc/001.phpt
tests/comparison_misc/002.phpt
tests/comparison_misc/003.phpt

Three miscellaneous tests from [JSONPath Comparison](https://cburgmer.github.io/json-path-comparison/):
- Empty selector
- Parens notation
- Script expression

Add some ungrouped tests from JSONPath Comparison

---

tests/comparison_bracket_notation/003.phpt
tests/comparison_bracket_notation/015.phpt
tests/comparison_bracket_notation/038.phpt
tests/comparison_bracket_notation/041.phpt
tests/comparison_bracket_notation/042.phpt
tests/comparison_bracket_notation/044.phpt
tests/comparison_dot_notation/012.phpt
tests/comparison_dot_notation/013.phpt
tests/comparison_dot_notation/014.phpt
tests/comparison_dot_notation/015.phpt
tests/comparison_dot_notation/016.phpt
tests/comparison_dot_notation/023.phpt
tests/comparison_dot_notation/036.phpt
tests/comparison_dot_notation/045.phpt
tests/comparison_dot_notation/046.phpt

https://github.com/supermetrics/php-ext-jsonpath/pull/25 fixed various things, especially related to recursive descent and wildcard iteration. Many more JSONPath Comparison tests now pass.

Fix bracket and dot notation JSONPath Comparison tests following switch to AST implementation

---

tests/comparison_union/001.phpt
tests/comparison_union/002.phpt
tests/comparison_union/003.phpt
tests/comparison_union/004.phpt
tests/comparison_union/005.phpt
tests/comparison_union/006.phpt
tests/comparison_union/007.phpt
tests/comparison_union/008.phpt
tests/comparison_union/009.phpt
tests/comparison_union/010.phpt
tests/comparison_union/011.phpt
tests/comparison_union/012.phpt
tests/comparison_union/013.phpt
tests/comparison_union/014.phpt
tests/comparison_union/015.phpt

Adds the 15 union tests from [JSONPath Comparison](https://cburgmer.github.io/json-path-comparison/), using the consensus result where there is one, and something that seems logical where there isn't consensus.
With this last set of JSONPath Comparison tests, the full test suite now contains 269 tests of which 80 are currently expected fails.

Add union tests from JSONPath Comparison tests

---

jsonpath.c
src/jsonpath/interpreter.c
src/jsonpath/interpreter.h
src/jsonpath/parser.c
src/jsonpath/parser.h
tests/expressions/002.phpt

@crocodele The following expression value (operands) types are supported:
- child selector
- number
- string
- regpattern
This PR aims to support jsonpaths within expressions, which requires fully recursive value evaluation.
Example:
```
$..book[?(@.author==$.authors[3])]
```
Changes:
- Move `evaluate_postfix_expression` from `parser.c` to `interpreter.c`
- Wrap expression values with an `AST_VALUE` struct. This makes it easier for the interpreter to know what nodes to send to `evaluate_ast`.
- Support JSONPaths as expression values. When the interpreter encounters a root selector `$` in an expression, it knows to send the JSONPath expression back to `evaluate_ast`. This requires `evaluate_ast` to have a reference to the beginning of the search target array (in addition to the current …

Support JSONPath subexpressions

---

tests/comparison_filter/041.phpt

Reverts supermetrics/php-ext-jsonpath#35
Seems this test behaves in different ways in PHP 7.4 (fails) and PHP 8.0 (passes).

Revert "Mark filter test 041 as passing following recent changes"

---

src/jsonpath/interpreter.c
src/jsonpath/parser.c
tests/comparison_filter/002.phpt
tests/comparison_filter/022.phpt

I fixed a segfault raised in `tests/comparison_filter/002.phpt` by `exec_expression`. The test passes after rearranging the expected test output. I'm not sure if the sorting expectations in `tests/comparison_filter/002.phpt` were erroneous, please advise @crocodele.

Fix tests/comparison_filter/{022,002}.phpt

---

src/jsonpath/interpreter.c
tests/comparison_bracket_notation/027.phpt
tests/comparison_dot_notation/032.phpt
tests/comparison_dot_notation/033.phpt

@crocodele This PR implements support for numeric selectors.
This fixes two tests:
* `tests/comparison_bracket_notation/027.phpt`
* `tests/comparison_dot_notation/033.phpt`
The change broke the expected value for `tests/comparison_dot_notation/032.phpt`. Because PHP automatically converts numeric string indexes to integer indexes, I don't think it's possible for this JSONPath implementation to differentiate between a numeric string index and an implicit index.
Observe below how all 3 arrays have an integer index type:
```php
$data1 = [
"first",
"second",
"third",
"forth",
"fifth",
];
var_dump(array_keys($data1));
/*
array(5) {
[0]=>
int(0)
[1]=>
int(1)
[2]=>
int(2)
[3]=>
int(3)
[4]=>
int(4)
}
*/
$data2 = [
0 => "first",
1 => "second",
2 => "third",
3 => "forth",
4 => "fifth",
]; …
```

Implement support for numeric selectors

---

src/jsonpath/parser.c
tests/comparison_filter/046.phpt
tests/isset/001.phpt
tests/isset/002.phpt
tests/isset/003.phpt

@crocodele 
Previously, the parser only checked if a selector was bordered on the
right side by a paren, OR operator or AND operator in order to determine
if the selector was an isset operand. This lead to edge cases where
selectors on the right side of binary expressions were incorrectly
getting treated as isset operands.
This commit implements a more robust check for isset operands.
As a result of this work, `tests/comparison_filter/046.phpt` now works.

Fix isset parsing edge cases

---

.build-scripts/compile-coverage.sh
.build-scripts/compile.sh
.github/workflows/code_coverage.yml
.gitignore
Makefile.gcov
config.m4
config.w32

This PR adds support for code coverage reports. The extension has to be compiled with the `--enable-code-coverage` flag for the tests to produce the code coverage reports.
Usage:
```
make clean
./configure --enable-jsonpath --enable-code-coverage --with-php-config=...
TEST_PHP_ARGS="-q" make test
make lcov
```
The above results in an HTML report in `lcov_html/`.
Also plugged into the GitHub Actions on merge to `main`, for showing a badge in README.

Add code coverage resolving with lcov

---

jsonpath.c
src/jsonpath/interpreter.c
src/jsonpath/lexer.c
src/jsonpath/lexer.h
tests/comparison_bracket_notation/030.phpt
tests/comparison_bracket_notation/036.phpt
tests/comparison_bracket_notation/046.phpt
tests/comparison_dot_notation/003.phpt
tests/comparison_dot_notation/050.phpt
tests/comparison_filter/004.phpt
tests/comparison_filter/019.phpt
tests/comparison_filter/049.phpt
tests/comparison_filter/050.phpt
tests/comparison_filter/058.phpt
tests/comparison_filter/072.phpt
tests/comparison_misc/002.phpt
tests/lex_errs/001.phpt
tests/lex_errs/002.phpt
tests/lex_errs/003.phpt
tests/lex_errs/004.phpt
tests/lex_errs/005.phpt
tests/overflow/001.phpt

@crocodele I'm planning to eventually remove all usage of legacy C string functions. This PR is a first pass at removing `strcpy` in the lexer.
The lexer now fails when it encounters an unknown character. As a result, 6 additional tests now pass.

Replace sprintf in lexer, fix 6 tests

---

jsonpath.c
src/jsonpath/lexer.c
src/jsonpath/parser.c
src/jsonpath/parser.h
tests/comparison_union/012.phpt
tests/comparison_union/013.phpt

@crocodele Throw an exception when expression filter list contains different separate types. Also remove legacy `strncpy()` from parser. Fixes two tests.

Fix tests/comparison_union/{012,013}.phpt

---

src/jsonpath/parser.c
tests/comparison_dot_notation/023.phpt
tests/comparison_dot_notation/036.phpt
tests/comparison_recursive_descent/001.phpt
tests/comparison_recursive_descent/002.phpt

@crocodele Throw an exception if a recursive descent operator is followed by an empty selector.
Note that in the case of `$..'key'`, the lexer stops reading the selector label once it hits the first `'`, hence why the selector is considered empty.

Require non-empty selector after recursive descent

---

jsonpath.c
src/jsonpath/interpreter.c
src/jsonpath/lexer.c
src/jsonpath/lexer.h
src/jsonpath/parser.c
src/jsonpath/parser.h
tests/comparison_filter/032.phpt
tests/comparison_filter/033.phpt
tests/comparison_filter/038.phpt
tests/comparison_filter/039.phpt
tests/comparison_filter/041.phpt
tests/comparison_filter/045.phpt

@crocodele I originally set out to fix just #53, but ended up implementing strict type and value checks in expressions (equivalent to `===` comparison in PHP I believe).
The nice thing here is that we're leveraging PHP's internal logic for doing numeric string conversion. The engine now parses long and double (including exponent notation) the same way PHP does.
These changes fix 6 additional unit tests.

Implement strict type+value checks, fix bool vals

---

tests/comparison_filter/023.phpt

With the correct key, the test now passes too thanks to the recent changes to the way values are compared.

Fix incorrect key in expected results for filter expression equals test

---

config.m4

The code coverage build flag was enabled by default and couldn't be disabled. Now works as expected.
`./configure ... --enable-jsonpath --enable-code-coverage`:
=>
```
checking whether to enable JSONPath support... yes, shared
checking whether to enable code coverage (relevant for extension development only!)... yes
``` 
`./configure ... --enable-jsonpath` or `./configure ... --enable-jsonpath --disable-code-coverage`:
=>
```
checking whether to enable JSONPath support... yes, shared
checking whether to enable code coverage (relevant for extension development only!)... no
```

Fix default value for --enable-code-coverage build flag

---

src/jsonpath/parser.c
tests/comparison_filter/053.phpt

Relates to https://github.com/supermetrics/php-ext-jsonpath/issues/51.
This is for handling this type of expressions: `$[?(@.key*2==100)]`
Currently the above leads to a `Missing closing paren )` error. By identifying the scenario where a node is followed by a wildcard, we can give a more specific error message.
The implementation feels slightly hacky, but I wasn't sure where else I could/should hook into the parsing steps to handle this.

Throw exception on multiplying node with numeric literal

---

tests/comparison_filter/061.phpt

This "test filter expression with single equal" test was fixed by https://github.com/supermetrics/php-ext-jsonpath/pull/72, similarly to the triple equal sign test.

Mark filter with simple equals sign test as fixed

---

src/jsonpath/parser.c
tests/comparison_filter/074.phpt

Relates to https://github.com/supermetrics/php-ext-jsonpath/issues/51.

Throw exception when parens are missing in filter expression

---

tests/comparison_filter/006.phpt
tests/comparison_filter/007.phpt
tests/comparison_filter/009.phpt
tests/comparison_filter/010.phpt

Closes https://github.com/supermetrics/php-ext-jsonpath/issues/57, though I'll move 007.phpt and 009.phpt to another issue for the numeracy check.

Mark two lone boolean tests as fixed, update expected failure message in two others to match expectations

---

src/jsonpath/interpreter.c
src/jsonpath/parser.c
tests/comparison_filter/007.phpt
tests/comparison_filter/009.phpt
tests/comparison_filter/047.phpt
tests/comparison_filter/048.phpt
tests/comparison_filter/051.phpt
tests/comparison_filter/052.phpt
tests/comparison_filter/055.phpt
tests/comparison_filter/056.phpt

Handle strict inequality checks as described in #59.

Return false when inequality contains dissimilar operand types

---

src/jsonpath/parser.c

Output of `tests/parse_errs/002.phpt` before:
```
Fatal error: Uncaught RuntimeException: Missing closing paren ) in /..../tests/parse_errs/002.php:5
Stack trace:
#0 /..../tests/parse_errs/002.php(5): JsonPath->find(Array, '$.store.book[?(...')
#1 {main}
thrown in /..../tests/parse_errs/002.php on line 5
[Thu May 13 02:22:55 2021]  Script:  '/..../tests/parse_errs/002.php'
/..../src/jsonpath/parser.c(55) :  Freeing 0x00007f639205e4d0 (72 bytes), script=/..../tests/parse_errs/002.php
Last leak repeated 2 times
=== Total 3 memory leaks detected ===
```

Fix memory leak on invalid filter expression (missing closing paren)

---

src/jsonpath/lexer.c
tests/comparison_dot_notation/022.phpt
tests/comparison_dot_notation/023.phpt
tests/comparison_dot_notation/035.phpt
tests/comparison_dot_notation/036.phpt
tests/comparison_dot_notation/037.phpt

Closes https://github.com/supermetrics/php-ext-jsonpath/issues/56.

Throw exception on dot or recursive descent operator followed by quoted string

---

README.md

Apparently the default branch name got reset from `main` to `master` when the repository was transferred. Will fix.

Sync master to main

---

jsonpath.c
src/jsonpath/lexer.c
tests/comparison_bracket_notation/025.phpt
tests/comparison_bracket_notation/026.phpt
tests/comparison_bracket_notation/029.phpt

The change in `extract_quoted_literal()` is to unescape quotes inside the string. It's invasive on the JSONPath expression string – removing escape-backslashes by shifting the whole remaining string one character to the left. I'm therefore taking a copy of the original parameter in `jsonpath.c`, so that the stack trace shows the original data without null characters or other oddities.
Not sure if this is the best way to do it, but everything else I tried basically failed due to string length mismatches, incorrect pointers etc.
Related to https://github.com/supermetrics-public/php-ext-jsonpath/issues/55.

Handle escaped quotes in string literals

---

jsonpath.c
src/jsonpath/interpreter.c
src/jsonpath/parser.c
src/jsonpath/parser.h
tests/comparison_filter/016.phpt
tests/comparison_filter/024.phpt

I am working on #63. Incidentally, fixing `tests/comparison_filter/024.phpt` (which is part of #63) also fixed `tests/comparison_filter/016.phpt`, which is assigned to you in #55 @crocodele.

Implement support for current object

---

src/jsonpath/interpreter.c
src/jsonpath/parser.c
tests/comparison_bracket_notation/037.phpt
tests/comparison_filter/013.phpt
tests/comparison_filter/014.phpt
tests/comparison_filter/015.phpt
tests/comparison_misc/003.phpt

- Support filters inside expressions. Fixes 2 tests.
- Fix negative index bug caused by overwritten AST node index value. Fixes 1 test.

Issue #63 - Support filters inside expressions, fix negative index bug

---

src/jsonpath/parser.c
tests/comparison_dot_notation/030.phpt

I changed the expected outcome of `tests/comparison_dot_notation/030.phpt` (test dot notation with key root literal, `$.$`) from returning the value to throwing an exception. It feels clearer IMHO, and this is one of those comparison tests that very much lack a consensus behavior.
So if the node name consists of letters, digits, dashes and underscores, one can use the dot selector. Any other characters => use the bracket notation.
Closes https://github.com/supermetrics-public/php-ext-jsonpath/issues/55.

Throw exception on root in dot selector node name

---

src/jsonpath/parser.c

With PHP in debug mode, I got two tests failing with a memory leak.
- tests/comparison_union/012.phpt
- tests/comparison_union/013.phpt

Fix memory leak in filter list parsing

---

jsonpath.c
src/jsonpath/interpreter.c
src/jsonpath/parser.c
src/jsonpath/parser.h
tests/comparison_dot_notation/049.phpt
tests/comparison_filter/035.phpt
tests/comparison_misc/001.phpt

I realized that implementing support for unions, array syntax and sets would be easier if I folded the rest of the parsing logic into the recursive descent parser pattern. This PR is a first pass at that effort. 
Some highlights:
- A net reduction in code
- Removed `sanity_check()`, `validate_parse_tree()`, `validate_root_next()`, which were kind of a band-aid for error handling. All the error checks are now done within the recursive descent parser.
- Removed dummy head node (not a big deal, but it bugged me)
I'm hoping to remove some of the redundant logic in `parse_primary()` in the next pass.

Refactor operators into recursive descent parser

---

src/jsonpath/interpreter.c
src/jsonpath/parser.c
tests/015.phpt
tests/016.phpt
tests/017.phpt
tests/018.phpt
tests/019.phpt
tests/020.phpt
tests/021.phpt
tests/overflow/003.phpt
tests/overflow/004.phpt
tests/regex/001.phpt
tests/regex/002.phpt
tests/regex/003.phpt

Some more tests and additional error handling here and there.
- Array slice with strings as start, end, and step
- Array slice with unquoted strings as start, end, and step
- Array slice with mix of unquoted string and numbers as start, end, and step
- Array slice with wildcard as end
- Broken boolean (`truse`) as right-hand operand
- Broken boolean (`falsue`) as left-hand operand
- Dot selector with misplaced current node operator
- Array slice with overflowing values for start, end, and stop
- Filter with overflowing operand
- Regex with broken regex pattern
Most of these came from analyzing the code coverage.

Fix various edge cases in error handling, with some added tests

---

src/jsonpath/interpreter.c
src/jsonpath/lexer.c
src/jsonpath/parser.c
tests/018.phpt
tests/comparison_filter/022.phpt
tests/comparison_filter/053.phpt
tests/comparison_union/015.phpt

Remove redundant logic in `parse_primary()`.
This change made detecting the `Multiplying node values is not supported` check impractical because it's difficult to keep track of whether a node selector followed by a wildcard falls within an expression. 
After thinking it over, I realized that `$[?(@.key*2==100)]` is arguably a lexing error rather than a parsing error. The only allowed wildcard syntax includes the following: `.*`, `..*` and `[*]`. Based on that, `@.key*2` is invalid. I moved this check into the lexer, where it returns `Unrecognized token...`. 
I think this is a bit cleaner than explicitly forbidding multiplication (why not subtraction, etc...). Let me know what you think.

Make parse_primary loop back into recursive descent parser

---

src/jsonpath/interpreter.c
src/jsonpath/lexer.c
src/jsonpath/parser.c
src/jsonpath/parser.h
tests/015.phpt
tests/comparison_bracket_notation/030.phpt
tests/comparison_bracket_notation/036.phpt
tests/comparison_dot_notation/020.phpt
tests/comparison_union/003.phpt
tests/comparison_union/005.phpt
tests/comparison_union/006.phpt
tests/comparison_union/007.phpt
tests/comparison_union/008.phpt
tests/comparison_union/009.phpt
tests/comparison_union/010.phpt
tests/lex_errs/001.phpt
tests/lex_errs/002.phpt

Implement support for union filter. Fixes 8 tests, improves error messages for others.
I will add bounds checking for the `len` and `string` members in the next PR.

Support union filter

---

src/jsonpath/interpreter.c
tests/022.phpt
tests/comparison_filter/028.phpt

Implement support for array expression filter operands.
Fixes segfault that occurs when invalid operand is present. Bubbles interpreter evaluation errors to top so user gets a more sane message.
This PR fixes two unit tests, which use string arrays. Numeric arrays are still unsupported (but the user now gets an exception instead of a segfault).

Support array expression filter operands

---

tests/comparison_union/004.phpt

As discussed in #52, we can choose not to support expressions with unions of filters.
Closes #52.

Expect exception in union with filter test

---

src/jsonpath/interpreter.c
src/jsonpath/lexer.c
tests/comparison_filter/019.phpt
tests/comparison_filter/057.phpt
tests/comparison_filter/058.phpt

Implement support for unquoted regex patterns, including patterns with escaped forward slashes.
I propose here that we do not support interpolating patterns, such as`/@.pattern/`. This doesn't seem like a widely supported feature and it would unnecessarily increase lexer complexity. LMK what you think.

Support unquoted regex patterns

---

.github/release-drafter.yml

This should give the PRs labels automatically based on branch names, PR titles, or the types of files changed. The labels are then used in the release draft.

Configure PR autolabeler for release drafting

---

src/jsonpath/lexer.c
src/jsonpath/parser.c
tests/comparison_recursive_descent/001.phpt
tests/comparison_recursive_descent/002.phpt

I moved the "Recursive descent operator `..` must be followed by a child selector, filter or wildcard" error to the lexer. I can't remember why I previously thought that the expression can end with a recursive descent operator, but it probably shouldn't.

Fix memory leak when expression ends with a lonely recursive descent operator

---

tests/comparison_filter/029.phpt
tests/comparison_filter/030.phpt
tests/comparison_filter/036.phpt
tests/comparison_filter/037.phpt
tests/comparison_filter/040.phpt
tests/comparison_filter/059.phpt
tests/comparison_filter/060.phpt
tests/comparison_filter/071.phpt

This PR fixes the remaining failed unit tests, most of which contain ambiguous JSONPath queries. I ended up setting the expected output to whatever the extension currently returns. (Note that the results from these ambiguous queries match the results given by other JSONPath libraries). Check out the commit messages and test descriptions for justifications.

Fix remaining unit tests

---

tests/023.phpt
tests/comparison_filter/057.phpt
tests/comparison_filter/058.phpt
tests/regex/002.phpt

So........there is a reasonable chance the alleged read from uninitialized memory is a false report: https://bugs.php.net/bug.php?id=81240 . In particular, as compiling with valgrind support makes the report dissapear it's more likely to be a false report than not.
Disabling the pcre.jit option also makes the issue go away. As you should be occcasionally testing to check for leaks, having the false reports not be there would be better than having people be confused by them.
There's a small chance the error alleged by valgrind is legitimate, and that it should be isolated and reported upstream. But I only have energy for this PR.

Disable PCRE jit to avoid alleged valgrind errors.

---

jsonpath.c

Use the Zend memory manager for allocating a copy of the jsonpath
string, as per the [PHP coding standards](https://raw.githubusercontent.com/php/php-src/master/CODING_STANDARDS.md).

Replace strdup->estrdup

---

LICENSE

LICENSE file contents copied from https://github.com/php/php-src/blob/master/LICENSE.

Change license from MIT to PHP to conform to PECL guidelines for PHP extensions

---

.github/workflows/clang_format_lint.yml

Fixes https://github.com/supermetrics-public/pecl-jsonpath/issues/125.

Perform clang-format check automatically on pushes to the repository

---

.github/workflows/code_coverage.yml
README.md

Relates to https://github.com/supermetrics-public/pecl-jsonpath/pull/128 and the PHP license terms.

Update links following repository name change

---

README.md

I missed this in https://github.com/supermetrics-public/pecl-jsonpath/pull/128.

Update license information in README to reflect license change from MIT to PHP

---

package.xml

* stub file is part of the project sources
* sort_recursively.php is required to run the test suite
* license uri is wrong (bad version, missing httpd)

missing file and license uri

---

package.xml

Should fix #135 on next PECL release.

Add missing config.w32 entry to package.xml to make PECL builds on Windows possible

---

.github/release-drafter.yml
Makefile.frag
tools/build-packagexml.php

This adds some automation and instructions on releasing new versions using `make release`. It includes the packaging and uploading of the new version to PECL. All based on a handy little script from https://gist.github.com/jasny/9eb02a0d1c6bc7e49aef29096799b202.
Fixes #136.

Add PECL release process

---

src/jsonpath/interpreter.c
tests/references/001.phpt
tests/references/002.phpt
tests/references/003.phpt
tests/references/004.phpt
tests/references/005.phpt
tests/references/006.phpt

Fixes #150, based on info in https://www.phpinternalsbook.com/php7/zvals/references.html.

Dereference values to always get the underlying value

---

src/jsonpath/interpreter.c

@crocodele Unfortunately my contribution today caused a 15% decrease in performance on the `$.artworks.*.title benchHugeDataset` benchmark, so I'm reverting the commit.

Revert "Issue #150 - pass AST_RECURSE token to exec_recursive_descent()"

---

config.w32
src/jsonpath/interpreter.c

First, we need to compile the ancillary files in the src/ directory.
Then we also need to cater to the local variable `s_lh`, what is
already defined as macro in WinSock2.h.  We could undefine that macro,
but just renaming the variable to `zs_lh` appears to be a good solution
either.

Fix Windows builds

---

.github/workflows/build.yml

shivammathur/setup-php (Linux) [supports PHP 8.2](https://github.com/shivammathur/setup-php#tada-php-support).
cmb69/setup-php-sdk (Windows) doesn't seem to support PHP 8.2 nightlies yet.

Include PHP 8.2 nightly as a version for test runs on Linux

---

jsonpath.c
src/jsonpath/lexer.c
src/jsonpath/lexer.h
src/jsonpath/parser.c
tests/issues/00164.phpt

This PR removes the string duplication (and string allocation) that occurs upon invoking `jsonpath()`, which was previously used to solve the [escaped string edge case](https://github.com/supermetrics-public/pecl-jsonpath/blob/main/tests/comparison_bracket_notation/025.phpt).
**Before**
`jsonpath()` duplicates the input string and passes it to the lexer. The lexer removes slashes from the string.
**After**
The lexer assigns tokens containing escaped characters the `LEX_LITERAL_UNESCAPED` type. When the parser encounters `LEX_LITERAL_UNESCAPED`, it runs the built-in `php_stripcslashes()` function on the allocated string.
I've also added a test that ensures string literal unescaping works. The existing tests in `tests/comparison_bracket_notation` only ensure that unescaping works on …

Issue #164 - refactor string unescaping

---

tests/comparison_root/003_php8.phpt
tests/comparison_root/004_php8.phpt

Without this
```
========DIFF========
001- Fatal error: Uncaught TypeError: JsonPath\JsonPath::find(): Argument #1 ($data) must be of type array, bool given in %s003_php8.php:%d
001+ Fatal error: Uncaught TypeError: JsonPath\JsonPath::find(): Argument #1 ($data) must be of type array, false given in /dev/shm/BUILD/php83-php-pecl-jsonpath-1.0.0/NTS/tests/comparison_root/003_php8.php:6
Stack trace:
%s
%s
--
========DONE========
FAIL Test root on scalar false [tests/comparison_root/003_php8.phpt] 
========DIFF========
001- Fatal error: Uncaught TypeError: JsonPath\JsonPath::find(): Argument #1 ($data) must be of type array, bool given in %s004_php8.php:%d
001+ Fatal error: Uncaught TypeError: JsonPath\JsonPath::find(): Argument #1 ($data) must be of type array, true given in …
```

relax test for 8.3

---

.github/workflows/build.yml
.github/workflows/clang_format_lint.yml
.github/workflows/code_coverage.yml
.github/workflows/windows.yml

Probably easiest to review with whitespace changes hidden.
- For Windows builds, changing the action from `cmb69/setup-php-sdk` to its successor (?) `php/setup-php-sdk`, which supports PHP 8.3 builds.
- Code coverage build is done with latest stable, i.e. PHP 8.3.

Test with PHP 8.3 on Windows, unify naming and formatting in workflow files

---

src/jsonpath/interpreter.c
tests/regex/004.phpt

Relates to #188.
I'm not very happy about the handling of booleans etc., but I don't think there's a perfect solution to that. If someone has ideas, feel free to suggest. By default, `true` would be cast to `"1"` and `false` to empty string `""`.

Fix segmentation fault when matching regex string against non-string values

---

.github/workflows/build.yml
.github/workflows/windows.yml

- PHP 8.4 requires a newer image than windows-2019, so let's try switching to windows-2022.
- php/setup-php-sdk@v0.10 introduced a cache option. Let's try it out.

Test also on PHP 8.4 for Windows and PHP 8.5 (nightly) for Linux, cache PHP-SDK in Windows

---

src/jsonpath/interpreter.c
tests/024.phpt
tests/025.phpt
tests/026.phpt
tests/comparison_filter/047.phpt
tests/comparison_filter/048.phpt
tests/comparison_filter/051.phpt
tests/comparison_filter/052.phpt
tests/comparison_filter/055.phpt

Related to issues (2.) and (3.) in https://github.com/supermetrics-public/pecl-jsonpath/issues/188.
This is a breaking change, so should be released as a new major version.

Allow numeric strings in number comparisons
